### ISSUE TITLE
Creating session object

### ISSUE THREAD

**Issue by maxxiefjv** [danni/python-pkcs11#112]
Hello, I am trying to create a new data object and aes key with identical labels using softhsm2 as pkcs module. The code looks as follows, and appears to succeed in the current session (I can find the dataobject in the same script). However, when inspecting the objects with either p11tool or by running another python-pkcs11 script, the data object seems to have disappeared.

```python
lib = pkcs11.lib('pkcs_module')
token = lib.get_token('token_label')
session = token.open(rw=True, user_pin=pin)

key = session.generate_key(pkcs11.KeyType.AES, 128, label='test', store=True)

dataobject = {
        pkcs11.Attribute.CLASS: pkcs11.ObjectClass.DATA,
        pkcs11.Attribute.LABEL: 'test',
        pkcs11.Attribute.VALUE: b'testing'
}

session.create_object(dataobject)

session.close()
```

The p11tool command ran: `p11tool --login --info <URL>`

There is no error message printed, and the only thing stored is the generated key. Is there something I am missing? 

Thanks

System:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
----
python 3.8.5
python-pkcs11 0.7.0
softhsm2-util 2.5.0
p11tool 3.6.13
```

**Comment by maxxiefjv** [comment]
For the sake of clarifying my intentions, the following workaround does the job. However, not how I would like to see it.

```bash
VALUE_FILE=$(mktemp -u /tmp/test.XXXXXXXXXX)
echo "Storing value in: $VALUE_FILE"

python -m tools.create_data_object $1 > $VALUE_FILE
LABEL=$(python -m tools.compute_label $1 || exit 1)

pkcs11-tool --module /usr/lib/softhsm/libsofthsm2.so -w $VALUE_FILE --label $LABEL --token-label token --type data
```

**Comment by danni** [comment]
Try setting `Attribute.TOKEN: True`, this is the equivalent of `store=True`.

**Comment by maxxiefjv** [comment]
Thank you, that is the trick indeed. I see it was documented. However I kindly suggest some additional information to improve the visibility of this particular attribute #113
