### ISSUE TITLE
RFC6979 support

### ISSUE THREAD

**Issue by alexpilk** [danni/python-pkcs11#115]
Is there any way to make an HSM sign a transaction deterministically using RFC6979 algorithm? 

The same way `sign_deterministic` works in the `ecdsa` package:
https://github.com/tlsfuzzer/python-ecdsa/blob/8dea392e9cc43d2f909a5283234679b921f0db94/src/ecdsa/keys.py#L1221

Thank you!

**Comment by danni** [comment]
Hi, you should direct this question at your HSM vendor. Thanks.
