### ISSUE TITLE
getting error while loadin library

### ISSUE THREAD

**Issue by lokeish** [danni/python-pkcs11#116]
lib = pkcs11.lib(os.environ['PKCS11_MODULE'])
after executing this command
getting this error RuntimeError: b'anaconda3/lib/python3.8/site-packages/pkcs11/__init__.py: invalid ELF header'
in PKCS11_MODULE , i given path like this anaconda3/lib/python3.8/site-packages/pkcs11/__init__.py
im using python version : **3.8.5**
how to solve this error?
Thank you!

**Comment by danni** [comment]
`PKCS11_MODULE` is the path to a binary, e.g. an `so` or a `dll`. The one supplied by your PKCS#11 vendor.
