### ISSUE TITLE
Unwrapped AES keys have key_length set to 0

### ISSUE THREAD

**Issue by ceridwen** [danni/python-pkcs11#120]
I'm not sure if I'm doing something wrong here, so this could be my fault.  I have some AES keys that were wrapped by another HSM that I'm trying to unwrap into SoftHSM.  I'm using RSA_PKCS_OAEP and AES_KEY_WRAP_PAD as the mechanisms for the wrapping.  The unwrap process seems to complete correctly and I get back a `pkcs11.Key` subclass, but key_length is set to 0:

```
            example_unwrapping_test = example_wrapping_softhsm.unwrap_key(pkcs11.ObjectClass.SECRET_KEY, pkcs11.KeyType.AES, example_blob, mechanism=pkcs11.Mechanism.RSA_PKCS_OAEP, store=True, label='example-unwrapping-test', template={
            pkcs11.Attribute.SENSITIVE: False,
            pkcs11.Attribute.EXTRACTABLE: True,
        })
        except Exception as error:
            print(error)
            print(vars(error))
            raise
        print(example_unwrapping_test)
        print(vars(example_unwrapping_test))
        print(len(example_unwrapping_test[pkcs11.Attribute.VALUE]))
```

```
<SecretKey label='example-unwrapping-test' id='' 0-bit AES>
{'session': <pkcs11._pkcs11.Session object at 0x7f0b2c8cd1d0>, '_handle': 8, 'label': 'example-unwrapping-test', 'id': b'', 'key_length': 0, 'key_type': <KeyType.AES>, '_key_description': '0-bit AES'}
32
```

Attribute.VALUE of the test key is the right length (32) and does have the same value as the test key before it was wrapped.  I tried passing in key_length to unwrap_key and got an error, so it doesn't seem like I can set it directly.  Do I have to set a value in the template somehow?

**Comment by danni** [comment]
`key_length` comes from the Attribute `VALUE_LEN`, which could be wrong, but it could also be a caching bug. Can you test what `Attribute.VALUE_LEN` returns for you?

**Comment by ceridwen** [comment]
Attribute.VALUE_LEN is also 0.

**Comment by danni** [comment]
Okay so that's coming from the HSM. There's not a lot to be done here from our side.

**Comment by ceridwen** [comment]
I posted this question to the SoftHSM people, https://github.com/opendnssec/SoftHSMv2/issues/628, and they told me to try passing CKA_VALUE_LEN in the template.  When I tried, I got this error:

```python
                secret=self.private.unwrap_key(
                    # RSA OAEP can only wrap symmetric keys
                    pkcs11.ObjectClass.SECRET_KEY,
                    pkcs11.KeyType.AES,
                    blob_file.read(),
                    mechanism=pkcs11.Mechanism.RSA_PKCS_OAEP,
                    store=True,
                    label=file_name + "-unwrapping-test",
                    # Test template
                    template={
                        pkcs11.Attribute.SENSITIVE: False,
                        pkcs11.Attribute.EXTRACTABLE: True,
                        pkcs11.Attribute.VALUE_LEN: 256,
                    },
```

```
Traceback (most recent call last):
  File "offline_example.py", line 542, in <module>
    'example-wrapped',
  File "offline_example.py", line 307, in unwrap_key
    pkcs11.Attribute.VALUE_LEN: 256,
  File "pkcs11/_pkcs11.pyx", line 1276, in pkcs11._pkcs11.UnwrapMixin.unwrap_key
  File "pkcs11/_errors.pyx", line 88, in pkcs11._pkcs11.assertRV
pkcs11.exceptions.AttributeReadOnly
```

I don't think this seems like correct behavior, though if you think it's SoftHSM that's misbehaving, I can go back to them.

**Comment by danni** [comment]
The response code also comes from the HSM.

**Comment by ceridwen** [comment]
Thank you for your patience.  I did get SoftHSM to confirm the problems are on their end.
