### ISSUE TITLE
Differentiate multiple certificates on a token

### ISSUE THREAD

**Issue by aschuster72** [danni/python-pkcs11#121]
First of all, I love you library. It helped me a lot in developing an HSM use case in python!

I see an issue when multiple certificate are on a token. When list all objects on a python-pkcs11 token the certificate objects does not return an ID or label.

In PKCS#11 this ID and label information seems to exist for certs as well, see the output of pkcs11-tool
```
$ pkcs11-tool --module /usr/lib/libsofthsm2.so -l --pin secret1 -O
Using slot 0 with a present token (0xd24c4d0)
Public Key Object; RSA 2048 bits
  label:      anotherkey
  ID:         010203
  Usage:      encrypt, verify, wrap
Certificate Object; type = X.509 cert
  label:      anotherkey
  subject:    DN: CN=ANOTHERTEST
  ID:         010203
Certificate Object; type = X.509 cert
  label:      test
  subject:    DN: CN=TEST
  ID:         a1b2
Private Key Object; RSA
  label:      anotherkey
  ID:         010203
  Usage:      decrypt, sign, unwrap
Private Key Object; RSA
  label:      test
  ID:         a1b2
  Usage:      decrypt, sign, unwrap
Public Key Object; RSA 2048 bits
  label:      test
  ID:         a1b2
  Usage:      encrypt, verify, wrap
```
Unfortunately the [ObjectClass.CERTIFICATE](https://python-pkcs11.readthedocs.io/en/latest/api.html?highlight=ObjectClass.CERTIFICATE#pkcs11.Certificate) in python-pkcs11 does not have the parameters id or label.

Best regards, Andreas

**Comment by danni** [comment]
So all attributes are accessible using the form `obj[Attribute.ID]`/`obj[Attribute.LABEL]`. We could probably move the properties for `label` onto `Object` (which is actually what the spec says), but `id` is not defined on any type of `Certificate` except X.509.

**Comment by aschuster72** [comment]
Thanks a lot Danni, the ID and LABEL is exactly where you suggested.
Please close this issue.

BR, Andreas
