### ISSUE TITLE
Can't sign using PIV + EC certificates

### ISSUE THREAD

**Issue by evergreeneverdeen** [danni/python-pkcs11#123]
Hi,

I'm trying to use this library to sign a string using a PIV card and its card authentication EC cert/key pair. For some reason, it seems that I am unable to run the sign function (library gives an error of `pkcs11.exceptions.MechanismInvalid`). Am I doing something wrong?

This is the code used:
```
import pkcs11

lib = pkcs11.lib("/usr/lib/opensc-pkcs11.so")
token = lib.get_token()

with token.open() as session:

    public = session.get_key(object_class = pkcs11.constants.ObjectClass.PUBLIC_KEY, id = b"\x04")
    private = session.get_key(object_class = pkcs11.constants.ObjectClass.PRIVATE_KEY, id = b"\x04")

    print(public)
    print(private)

    data = "test"
    signature = private.sign(data)
```

Output/error:
```
<PublicKey label='CARD AUTH pubkey' id='04' EC>
<PrivateKey label='CARD AUTH key' id='04' EC>
Traceback (most recent call last):
  File "./test.py", line 16, in <module>
    signature = private.sign(data)
  File "/usr/local/lib/python3.8/dist-packages/pkcs11/types.py", line 939, in sign
    return self._sign(data, **kwargs)
  File "pkcs11/_pkcs11.pyx", line 1072, in pkcs11._pkcs11.SignMixin._sign
  File "pkcs11/_pkcs11.pyx", line 1074, in pkcs11._pkcs11.SignMixin._sign
  File "pkcs11/_errors.pyx", line 88, in pkcs11._pkcs11.assertRV
pkcs11.exceptions.MechanismInvalid
```
(I've also tried explicitly specifying `ECDSA` and `ECDSA_SHA256` as the mechanism in `private.sign()`, both of which failed. However, when plain `ECDSA` is used, I got an error of `pkcs11.exceptions.DataInvalid` instead.)

This is the certificate (the only card I have right now uses EC certificates, so I'm not sure if this will be different with RSA):
```
$ pkcs15-tool --read-certificate 04 | openssl x509 -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            [redacted]
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: [redacted]
        Validity
            Not Before: [redacted]
            Not After : [redacted]
        Subject: [redacted]
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    [public key]
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Subject Alternative Name:
                [redacted]
    Signature Algorithm: ecdsa-with-SHA256
         [signature]
```

Thanks in advance!

**Comment by danni** [comment]
There is a default mechanism for each key type. Check that mechanism is available to you via `slot.get_mechanisms`.

`DataInvalid` means the plaintext is in the wrong format. Normally that means the wrong length for the mechanism. Padding, hashing, etc. beyond what is supplied by the HSM are all beyond the scope of Python-PKCS11 and should be handled via the cryptographic primitives library of your choice.

**Comment by evergreeneverdeen** [comment]
Ah, I see. Apparently my card doesn't support any of the `ECDSA_SHA*` mechanisms:

```
{<Mechanism.RSA_PKCS>, <Mechanism.RSA_X_509>, <Mechanism.MD5_RSA_PKCS>, <Mechanism.SHA1_RSA_PKCS>, <Mechanism._RIPEMD160_RSA_PKCS>, <Mechanism.RSA_PKCS_PSS>, <Mechanism.SHA1_RSA_PKCS_PSS>, <Mechanism._MD5>, <Mechanism.GOSTR3411>, <Mechanism.SHA_1>, <Mechanism._RIPEMD160>, <Mechanism.ECDSA>, <Mechanism.SHA256_RSA_PKCS>, <Mechanism.SHA384_RSA_PKCS>, <Mechanism.SHA512_RSA_PKCS>, <Mechanism.SHA256_RSA_PKCS_PSS>, <Mechanism.SHA224_RSA_PKCS>, <Mechanism.SHA224_RSA_PKCS_PSS>, <Mechanism.SHA384_RSA_PKCS_PSS>, <Mechanism.SHA512_RSA_PKCS_PSS>, <Mechanism.SHA256>, <Mechanism.ECDH1_COFACTOR_DERIVE>, <Mechanism.ECDH1_DERIVE>, <Mechanism.SHA224>, <Mechanism.SHA384>, <Mechanism.SHA512>}
```

That being said, I tried changing the sign/verify code to:
```
data = hashlib.sha512(str("test").encode("utf-8")).digest()
signature = private.sign(data, mechanism=pkcs11.Mechanism.ECDSA)
verify = public.verify(data, signature, mechanism=pkcs11.Mechanism.ECDSA)
```

I'm still getting the `MechanismInvalid` error, despite `ECDSA` being on the list of supported mechanisms and the sign step went through (though the error is on the verification step). Would you happen to know what might be wrong here?

```
Traceback (most recent call last):
  File "./test.py", line 18, in <module>
    verify = public.verify(datahash, signature, mechanism=pkcs11.Mechanism.ECDSA)
  File "/usr/local/lib/python3.8/dist-packages/pkcs11/types.py", line 979, in verify
    self._verify(data, signature, **kwargs)
  File "pkcs11/_pkcs11.pyx", line 1148, in pkcs11._pkcs11.VerifyMixin._verify
  File "pkcs11/_pkcs11.pyx", line 1150, in pkcs11._pkcs11.VerifyMixin._verify
  File "pkcs11/_errors.pyx", line 88, in pkcs11._pkcs11.assertRV
pkcs11.exceptions.MechanismInvalid
```

**Comment by danni** [comment]
Oh, it's not just a list of mechanisms. Each mechanism will have a bitwise flag of supported operations. It's pretty common for many chip-HSMs not to support the public side of PKI. e.g. if you don't need secret material, they don't implement the mechanism.

In these cases you should download the public key/certificate and do the validation yourself via the crypto library of your choice.

**Comment by evergreeneverdeen** [comment]
Ah. Thanks again!
