### ISSUE TITLE
Correct MAC Mechanism for SoftHSMv2

### ISSUE THREAD

**Issue by Ovomaltine85** [danni/python-pkcs11#13]
Hi,

I'm using softhsmv2 (2.3.0) as underlying HSM, where I have a secret AES key (256 bit) stored on a token. Encryption and Decryption works so far with the default mechanism AES_CBC_PAD.

But if I want to use the MAC functionality I got problems with the regarding mechanism. The docu says that AES_MAC is used by default. But softhsmv2 does not offer it. If I print the list of the provided mechanisms I got some like "SHA256_HMAC" etc. but not AES_MAC. When I use SHA256_HMAC with my 256 bit AES key, I get an KeyTypeInconsistent exception. If I use AES_MAC then it says MechanismInvalid.

How can I achieve signing/MAC-creation? 

Thank you!

**Comment by danni** [comment]
So the PKCS#11 spec says you can't use an AES key for HMAC, which SoftHSM2 recently started enforcing. Try a [`SHA256_HMAC`](http://python-pkcs11.readthedocs.io/en/latest/api.html#pkcs11.mechanisms.KeyType.SHA256_HMAC) key.

Reading the SoftHSM2 source, you can also use `GENERIC_SECRET`:

	case CKM_SHA256_HMAC:
		if (keyType != CKK_GENERIC_SECRET && keyType != CKK_SHA256_HMAC)
			return CKR_KEY_TYPE_INCONSISTENT;
		minSize = 32;

I'm not aware of a mechanism to change a key type without extracting it and reloading it. You can derive additional symmetric keys from an AES key using [`CKM_AES_ECB_ENCRYPT_DATA`](https://www.cryptsoft.com/pkcs11doc/v220/group__SEC__12__14__KEY__DERIVATION__BY__DATA__ENCRYPTION______DES______AES.html) but someone needs to test if it's supported. Also the choice of input data requires consideration if you want to avoid inventing a new cryptographic mechanism.
