### ISSUE TITLE
Small Typo in _pkcs11.pyx

### ISSUE THREAD

**Issue by kalebmckale** [danni/python-pkcs11#147]
https://github.com/danni/python-pkcs11/blob/e35e6c45e3dcaaa1511262121ff4ab6769de941e/pkcs11/_pkcs11.pyx#L380

Shouldn’t this line read
```python
cdef CK_SESSION_HANDLE handle = self._handle
```
instead?

**Comment by kalebmckale** [comment]
Just wanted to ping this issue to see if this is something that merits an PR or not. @danni

**Comment by danni** [comment]
Yes, please. Good catch.

**Comment by kalebmckale** [comment]
Thanks! What you've created here is pretty awesome, and I've learned so much just reading through your code, which is how I stumbled up on it. Will create a minor PR for it.

**Comment by danni** [comment]
Thanks :)

**Comment by kalebmckale** [comment]
@danni Done!
