### ISSUE TITLE
Problems with Mechanism during MAC operations

### ISSUE THREAD

**Issue by Ovomaltine85** [danni/python-pkcs11#17]
Hi,
I'm using softhsmv2 (2.3.0) as the underlying HSM. I want to use a symmetric key that is stored in the HSM to create a HMAC for a hash value (binary format). 
If I do the following:
`aes_key_handle.sign(hashed_data, mechanism=pkcs11.Mechanism.SHA256_HMAC)`
I get a KeyTypeInconsistent exception.
If I do the following:
`aes_key_handle.sign(hashed_data)`
I get a MechanismInvalid exception.

The mechanism SHA256_HMAC is supported by the HSM (shown via slot.get_mechanisms()).
I'm using the current version (0.5.0) of python-pkcs11 together with python3.

Can you tell want went wrong or where the error is?

Thank you very much for your help and your great lib!

**Comment by danni** [comment]
A recent change to SoftHSM means you can no longer use the generic HMAC mechanisms with AES keys, you need to use the `GENERIC_SECRET` key type or use an AES signing mechanism. SoftHSM does not support the default `AES_MAC` so you need to use something like `AES_CMAC` (supported in master).
