### ISSUE TITLE
Question about load the token driver

### ISSUE THREAD

**Issue by franciscolfilho** [danni/python-pkcs11#19]
Hi,
    Congratulations for your work. I started studying Python a few weeks ago.
    I've used the PyKCS11 package successfully, but I'm interested in studying your package.
    Please, I need help about loading the token driver, in snippet below:

import pkcs11
lib = pkcs11.lib("/usr/lib64/libaetpkss.so.3")

   It is being reported:

Traceback (most recent call last):
  File "/home/falf/eclipse-workspace/MyProject/FindingTokens.py", line 6, in <module>
    lib = pkcs11.lib("/usr/lib64/libaetpkss.so.3")
  File "/usr/lib64/python2.7/site-packages/pkcs11/__init__.py", line 36, in lib
    _lib = _pkcs11.lib(so)
  File "pkcs11/_pkcs11.pyx", line 1179, in pkcs11._pkcs11.lib.__init__
TypeError: Expected str, got unicode
 
  Sorry if I posted my question in a wrong place. I am using Python 2.7 on centos 7.
  Have you have any ideas?

Thank you,
Francisco

**Comment by danni** [comment]
Hi, python-pkcs11 does not work in Python 2.7. The motivation for writing it was Python 3 support and the so it only supports Python 3 features. I do not recommend writing any new Python 2.7 code, but if you must then PyKCS11 is your only choice.

Warm regards,
--danni
