### ISSUE TITLE
Get Slot by ID

### ISSUE THREAD

**Issue by ftbarata** [danni/python-pkcs11#22]
Hi everyone, I'm trying to get a slot by an ID. I tried some ways to do it, unsuccessfully.

**Comment by danni** [comment]
You'll have to iterate out the slots and filter by `slot.slot_id`. However I don't recommend it, slot IDs are not well defined in PKCS#11, and are often a reflection of system state. Consider using the token ID or token name, which are values stored in the token.

**Comment by ftbarata** [comment]
Thank you @danni !
