### ISSUE TITLE
Segmentation fault with SafeNet/Gemalto IDPrime MD 830 B

### ISSUE THREAD

**Issue by 01000101** [danni/python-pkcs11#24]
**smartcards/test.py**
```python
import pkcs11


def main():
  """ Entry point """
  # Initialise the PKCS#11 library
  print 'Attempting to load PKCS#11 module'
  lib = pkcs11.lib('/usr/lib64/libIDPrimePKCS11.so')
  print 'Library loaded'


if __name__ == '__main__':
  main()
```

**Running the script produces a segfault**
```bash
(venv) [cerealkiller@thegibson Dev]$ python smartcards/test.py
Attempting to load PKCS#11 module
Segmentation fault (core dumped)
```

**PIP information**
```
(venv) [cerealkiller@thegibson Dev]$ pip --version
pip 10.0.1 from /home/cerealkiller/Desktop/Dev/venv/lib/python2.7/site-packages/pip (python 2.7)
(venv) [cerealkiller@thegibson Dev]$ pip show python-pkcs11
Name: python-pkcs11
Version: 0.5.0
Summary: PKCS#11 (Cryptoki) support for Python
Home-page: https://github.com/danni/python-pkcs11
Author: Danielle Madeley
Author-email: danielle@madeley.id.au
License: UNKNOWN
Location: /home/cerealkiller/Desktop/Dev/venv/lib/python2.7/site-packages
Requires: aenum, asn1crypto, cached-property
Required-by: 
```

**Smartcard information**
Note, this is using the latest SafeNet Authentication Client (10.0-post-ga for Linux). I use this card daily with many other services / software such as p11tool, OpenSSL, OpenSSH, and web browser for client authentication. This card is *not* compatible with OpenSC or its kind but I've never seen any other software segfault when using this PKCS#11 module. 
```
(venv) [cerealkiller@thegibson Dev]$ p11tool --list-tokens
...

Token 2:
	URL: pkcs11:model=ID%20Prime%20MD;manufacturer=Gemalto;serial=XXXXXXXXXXXXXX;token=Gemalto%20IDPrime%20830%20B%20%2b%20Mifare%204
	Label: Gemalto IDPrime 830 B + Mifare 4
	Type: Hardware token
	Flags: RNG, Requires login
	Manufacturer: Gemalto
	Model: ID Prime MD
	Serial: XXXXXXXXXXXXXXX
	Module: /usr/lib64/libIDPrimePKCS11.so
```

I'd be happy to provide traces / OS segfault reports if needed. Thanks in advance!

**Comment by danni** [comment]
Hi,

python-pkcs11 is only usable with Python 3. **Python 2.x is not supported**. It shouldn't even be compilable with Python 2.7, so I'm not sure how you got this far.

**Comment by 01000101** [comment]
I got this far by running `pip install python-pkcs11`. 
Not exactly a weird hack...

**Comment by danni** [comment]
Strange, that used to fail in Python 2.x. It's possible you have a python 3 pre-compiled version. I'm not sure. Give it a go in Python 3.

**Comment by redNixon** [comment]
I've ran into this when installing other py3-only projects since Ubuntu uses python2 as the default(apt will randomly move symlink to pip to the wrong version for some reason after updating even if you make py3 preferred).

Using `pip3 install python-pkcs11` is the easiest way to make sure it is actually doing what you think it is doing.
