### ISSUE TITLE
Segmentation fault (core dumped) public.verify(data, signature)

### ISSUE THREAD

**Issue by ftbarata** [danni/python-pkcs11#26]
When trying to verify the signature, it throws segmentation fault error. Any ideas?

 try:
                for token in lib.get_tokens():
                    if token.serial.decode() == serial:
                        with token.open(user_pin=pin) as session:
                            priv = session.get_key(object_class=pkcs11.constants.ObjectClass.PRIVATE_KEY)
                            pub = session.get_key(object_class=pkcs11.constants.ObjectClass.PUBLIC_KEY)
                            data = token.serial.decode()
                            signature = priv.sign(data, mechanism=pkcs11.Mechanism.SHA256_RSA_PKCS)
                            print(pub.verify(data, signature))
 except TokenNotPresent:
    pass

**Comment by ftbarata** [comment]
Hi @danni ! It does not print the stack trace. How could I get it to give you?
The encrypt method throws the same error too.

**Comment by danni** [comment]
You'll need `cydb` and then do a `cy bt` in your app when it crashes. See https://cython.readthedocs.io/en/latest/src/userguide/debugging.html

However, given it's both verify and encrypt that don't work I'm guessing your device doesn't support them and we're crashing because the symbols don't resolve or something similar.

**Comment by ftbarata** [comment]
@danni , take a look:

pkcs11-tool --module /lib/libeToken.so.9 --id d4df2b4a82793ed0  -l --pin **** -M
Using slot 0 with a present token (0x0)
Supported mechanisms:
  DES-MAC, keySize={8,8}, sign, verify
  DES-MAC-GENERAL, keySize={8,8}, sign, verify
  DES3-MAC, keySize={24,24}, sign, verify
  DES3-MAC-GENERAL, keySize={24,24}, sign, verify
  AES-MAC, keySize={16,32}, sign, verify
  AES-MAC-GENERAL, keySize={16,32}, sign, verify
  RC4, keySize={8,2048}, encrypt, decrypt
  DES-ECB, keySize={8,8}, encrypt, decrypt, wrap, unwrap
  DES-CBC, keySize={8,8}, encrypt, decrypt, wrap, unwrap
  DES-CBC-PAD, keySize={8,8}, encrypt, decrypt, wrap, unwrap
  DES3-ECB, keySize={24,24}, hw, encrypt, decrypt, wrap, unwrap
  DES3-CBC, keySize={24,24}, hw, encrypt, decrypt, wrap, unwrap
  DES3-CBC-PAD, keySize={24,24}, hw, encrypt, decrypt, wrap, unwrap
  AES-ECB, keySize={16,32}, hw, encrypt, decrypt, wrap, unwrap
  AES-CBC, keySize={16,32}, hw, encrypt, decrypt, wrap, unwrap
  AES-CBC-PAD, keySize={16,32}, hw, encrypt, decrypt, wrap, unwrap
  mechtype-4230, keySize={16,32}, hw, encrypt, decrypt, wrap, unwrap
  mechtype-4232, keySize={16,32}, hw, encrypt, decrypt, wrap, unwrap
  RSA-PKCS-KEY-PAIR-GEN, keySize={1024,2048}, hw, generate_key_pair
  RSA-PKCS, keySize={1024,2048}, hw, encrypt, decrypt, sign, sign_recover, verify, verify_recover, wrap, unwrap
  RSA-PKCS-OAEP, keySize={1024,2048}, hw, encrypt, decrypt, wrap, unwrap
  RSA-PKCS-PSS, keySize={1024,2048}, hw, sign, verify
  SHA1-RSA-PKCS-PSS, keySize={1024,2048}, hw, sign, verify
  mechtype-67, keySize={1024,2048}, hw, sign, verify
  mechtype-68, keySize={1024,2048}, hw, sign, verify
  mechtype-69, keySize={1024,2048}, hw, sign, verify
  MD5-RSA-PKCS, keySize={1024,2048}, hw, sign, verify
  SHA1-RSA-PKCS, keySize={1024,2048}, hw, sign, verify
  SHA256-RSA-PKCS, keySize={1024,2048}, hw, sign, verify
  SHA384-RSA-PKCS, keySize={1024,2048}, hw, sign, verify
  SHA512-RSA-PKCS, keySize={1024,2048}, hw, sign, verify
  ECDSA-KEY-PAIR-GEN, keySize={256,384}, hw, generate_key_pair, other flags=0xd00000
  ECDSA, keySize={256,384}, hw, sign, verify, other flags=0xd00000
  ECDSA-SHA1, keySize={256,384}, hw, sign, verify, other flags=0xd00000
  mechtype-4164, keySize={256,384}, hw, sign, verify, other flags=0xd00000
  mechtype-4165, keySize={256,384}, hw, sign, verify, other flags=0xd00000
  mechtype-2147483717, keySize={256,384}, hw, sign, verify, other flags=0xd00000
  mechtype-4166, keySize={256,384}, hw, sign, verify, other flags=0xd00000
  ECDH1-DERIVE, keySize={256,384}, hw, derive, other flags=0xd00000
  RC4-KEY-GEN, keySize={8,2048}, generate
  DES-KEY-GEN, keySize={8,8}, generate
  DES2-KEY-GEN, keySize={16,16}, generate
  DES3-KEY-GEN, keySize={24,24}, generate
  AES-KEY-GEN, keySize={16,32}, generate
  PBE-SHA1-RC4-128, keySize={128,128}, generate
  PBE-SHA1-RC4-40, keySize={40,40}, generate
  PBE-SHA1-DES3-EDE-CBC, keySize={24,24}, generate
  PBE-SHA1-DES2-EDE-CBC, keySize={16,16}, generate
  GENERIC-SECRET-KEY-GEN, keySize={8,2048}, hw, generate
  PBA-SHA1-WITH-SHA1-HMAC, keySize={160,160}, hw, generate
  PBE-MD5-DES-CBC, keySize={8,8}, generate
  PKCS5-PBKD2, generate
  MD5-HMAC-GENERAL, keySize={8,2048}, sign, verify
  MD5-HMAC, keySize={8,2048}, sign, verify
  SHA-1-HMAC-GENERAL, keySize={8,2048}, sign, verify
  SHA-1-HMAC, keySize={8,2048}, sign, verify
  mechtype-594, keySize={8,2048}, sign, verify
  mechtype-593, keySize={8,2048}, sign, verify
  mechtype-610, keySize={8,2048}, sign, verify
  mechtype-609, keySize={8,2048}, sign, verify
  mechtype-626, keySize={8,2048}, sign, verify
  mechtype-625, keySize={8,2048}, sign, verify
  MD5, digest
  SHA-1, digest
  SHA256, digest
  SHA384, digest
  SHA512, digest
  mechtype-2147508225, keySize={24,24}, generate

So many mechanisms support sign and verify capabilities, including SHA256_RSA_PKCS

What do you think? I will try to get the stack trace if you still need.

**Comment by danni** [comment]
So it's possible for the mechanism list to be wrong, and for the device not to return `MechanismInvalid`. It really depends on the quality of the PKCS#11 driver. Especially if your token is baked into your device with fixed keys, why does it support all of these mechanisms?

Still I'd be keen to see the backtrace just so we can know for certain.
