### ISSUE TITLE
PKCS11 library is incorrectly used

### ISSUE THREAD

**Issue by fzonneveld** [danni/python-pkcs11#27]
It is assumed that the PKCS#11 library contains symbols like C_WrapKey and C_UnwrapKey. This is wrong, these function should accessed indirectly with the return value of C_GetFunctionList.
SoftHSMV2 supplies all these symbols in the softhsm2.so, but when using a pkcs11-proxy to forward all the requests over the network, the loading of the pkcs11-proxy.so library fails. 
$ objdump  -T /usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so | grep " C_"
This shows all the available symbols for the 
$ objdump  -T /usr/lib/libpkcs11-proxy.so  | grep " C_" 
This show only the C_GetFunctionList.

**Comment by danni** [comment]
Yep I'm aware of this. In general the dynamic loading should be reworked to make it easier to support Windows as well. Also not every implementation offers all the symbols, and you currently SEGV if you try to use a symbol that is not supplied by the library, e.g. encrypt on Nitrokey.

**Comment by fzonneveld** [comment]
This has got nothing to do with Windows or linux. I am using linux for all. The problem is that these symbols  that you describe should not be used, but only the C_GetFunctionList should be used. The result of this function return a list of function pointers, where non supprted functions are set to to a function which return CKR_FUNCTION_NOT_SUPPORTED. All this is clearly specified in http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html
Assumption that a PKCS#11 compatible library exposes other symbols like for example C_Encrypt is wrong.

**Comment by danni** [comment]
Yes I understand. I'm saying this fix would also help resolve an issue with Windows in general.

**Comment by danni** [comment]
Fixed in #32
