### ISSUE TITLE
Cannot load OpenSC PKCS#11 Library on Ubuntu 16.04

### ISSUE THREAD

**Issue by mgramigna** [danni/python-pkcs11#29]
I am using [OpenSC's PKCS#11](https://github.com/OpenSC/OpenSC) as the `.so` file that I pass into `pkcs11.lib` to setup `python-pkcs11`. I get the following error:

```
>>> pkcs11.lib(os.environ['PKCS11_MODULE'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/python_pkcs11-0.5.0-py3.5-linux-x86_64.egg/pkcs11/__init__.py", line 34, in lib
    from . import _pkcs11
ImportError: /usr/local/lib/python3.5/dist-packages/python_pkcs11-0.5.0-py3.5-linux-x86_64.egg/pkcs11/_pkcs11.cpython-35m-x86_64-linux-gnu.so: undefined symbol: C_UnwrapKey
```

Is this an OpenSC problem, or a problem with the `python-pkcs11` module? I also tried loading OpenSC's module using `python-pkcs11` on my Mac instead of Ubuntu and it worked fine.

**Comment by danni** [comment]
Python PKCS#11 doesn't currently play nicely with missing symbols. Which is bug #27.
