### ISSUE TITLE
pip install fails on CYGWIN

### ISSUE THREAD

**Issue by migrundmann** [danni/python-pkcs11#30]
ld fails :

gcc -shared -Wl,--enable-auto-image-base -L. build/temp.cygwin-2.11.2-x86_64-2.7/pkcs11/_pkcs11.o -L/usr/lib/python2.7/config -L/usr/lib -lpython2.7 -o build/lib.cygwin-2.11.2-x86_64-2.7/pkcs11/_pkcs11.dll
    build/temp.cygwin-2.11.2-x86_64-2.7/pkcs11/_pkcs11.o : Dans la fonction « __pyx_pf_6pkcs11_7_pkcs11_3lib_15__dealloc__ » :
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:24855 : référence indéfinie vers « C_Finalize »
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:24855:(.text+0x22cd3): relocalisation tronquée pour concorder avec la taille : R_X86_64_PC32 vers le symbole indéfini C_Finalize
    build/temp.cygwin-2.11.2-x86_64-2.7/pkcs11/_pkcs11.o : Dans la fonction « __pyx_pf_6pkcs11_7_pkcs11_11UnwrapMixin_unwrap_key » :
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:21464 : référence indéfinie vers « C_UnwrapKey »
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:21464:(.text+0x2445e): relocalisation tronquée pour concorder avec la taille : R_X86_64_PC32 vers le symbole indéfini C_UnwrapKey
    build/temp.cygwin-2.11.2-x86_64-2.7/pkcs11/_pkcs11.o : Dans la fonction « __pyx_pf_6pkcs11_7_pkcs11_6Object_8destroy » :
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:14071 : référence indéfinie vers « C_DestroyObject »
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:14071:(.text+0x267f8): relocalisation tronquée pour concorder avec la taille : R_X86_64_PC32 vers le symbole indéfini C_DestroyObject
    build/temp.cygwin-2.11.2-x86_64-2.7/pkcs11/_pkcs11.o : Dans la fonction « __pyx_pf_6pkcs11_7_pkcs11_6Object_4__setitem__ » :
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:13773 : référence indéfinie vers « C_SetAttributeValue »
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:13773:(.text+0x26fc2): relocalisation tronquée pour concorder avec la taille : R_X86_64_PC32 vers le symbole indéfini C_SetAttributeValue
    build/temp.cygwin-2.11.2-x86_64-2.7/pkcs11/_pkcs11.o : Dans la fonction « __pyx_pf_6pkcs11_7_pkcs11_7Session_16generate_random » :
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:11547 : référence indéfinie vers « C_GenerateRandom »
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:11547:(.text+0x283ea): relocalisation tronquée pour concorder avec la taille : R_X86_64_PC32 vers le symbole indéfini C_GenerateRandom
    build/temp.cygwin-2.11.2-x86_64-2.7/pkcs11/_pkcs11.o : Dans la fonction « __pyx_pf_6pkcs11_7_pkcs11_7Session_14seed_random » :
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:11393 : référence indéfinie vers « C_SeedRandom »
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:11393:(.text+0x29253): relocalisation tronquée pour concorder avec la taille : R_X86_64_PC32 vers le symbole indéfini C_SeedRandom
    build/temp.cygwin-2.11.2-x86_64-2.7/pkcs11/_pkcs11.o : Dans la fonction « __pyx_pf_6pkcs11_7_pkcs11_7Session_12_generate_keypair » :
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:11128 : référence indéfinie vers « C_GenerateKeyPair »
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:11128:(.text+0x2b304): relocalisation tronquée pour concorder avec la taille : R_X86_64_PC32 vers le symbole indéfini C_GenerateKeyPair
    build/temp.cygwin-2.11.2-x86_64-2.7/pkcs11/_pkcs11.o : Dans la fonction « __pyx_pf_6pkcs11_7_pkcs11_7Session_10generate_key » :
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:9840 : référence indéfinie vers « C_GenerateKey »
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:9840:(.text+0x2fb63): relocalisation tronquée pour concorder avec la taille : R_X86_64_PC32 vers le symbole indéfini C_GenerateKey
    build/temp.cygwin-2.11.2-x86_64-2.7/pkcs11/_pkcs11.o : Dans la fonction « __pyx_pf_6pkcs11_7_pkcs11_7Session_4create_object » :
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:7890 : référence indéfinie vers « C_CreateObject »
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:7890:(.text+0x31f8f): relocalisation tronquée pour concorder avec la taille : R_X86_64_PC32 vers le symbole indéfini C_CreateObject
    build/temp.cygwin-2.11.2-x86_64-2.7/pkcs11/_pkcs11.o : Dans la fonction « __pyx_pf_6pkcs11_7_pkcs11_7Session_close » :
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:7546 : référence indéfinie vers « C_Logout »
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:7546:(.text+0x32ca2): relocalisation tronquée pour concorder avec la taille : R_X86_64_PC32 vers le symbole indéfini C_Logout
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:7568 : référence indéfinie vers « C_CloseSession »
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:7568:(.text+0x32d23): débordement de relocalisation additionnelle omise à partir de la sortie
    build/temp.cygwin-2.11.2-x86_64-2.7/pkcs11/_pkcs11.o : Dans la fonction « __pyx_pf_6pkcs11_7_pkcs11_10SearchIter_8_finalize » :
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:7413 : référence indéfinie vers « C_FindObjectsFinal »
    build/temp.cygwin-2.11.2-x86_64-2.7/pkcs11/_pkcs11.o : Dans la fonction « __pyx_pf_6pkcs11_7_pkcs11_4Slot_4get_mechanism_info » :
    /tmp/pip-install-GnPBKp/python-pkcs11/pkcs11/_pkcs11.c:6300 : référence indéfinie vers « C_GetMechanismInfo »
    build/temp.cygwin-2.11.2-x86_64-2.7/pkcs11/_pkcs11.o : Dans la fonction « __pyx_pf_6pkcs11_7_pkcs11_4Slot_get_token » :

**Comment by migrundmann** [comment]
symbols like C_FindObjectsFinal ,  C_Logout, C_GenerateKey are undefined during the linkage on CYGWIN

**Comment by danni** [comment]
This looks suspiciously like bug #27
