### ISSUE TITLE
No sign method created on imported private key object

### ISSUE THREAD

**Issue by conscott** [danni/python-pkcs11#31]
Playing with signing with imported DER private key, and the object returned from create_object() contains no `sign` method. 

```
with token.open(rw=True, user_pin=os.environ['PIN']) as session:
        pk = ec.decode_ec_private_key(data)
        pk[Attribute.LABEL] = label
        pk[Attribute.TOKEN] = True
        pk[Attribute.SIGN] = True
        obj = session.create_object(pk)
        der_sig = obj.sign(data) # Fails here
```
Fails with `AttributeError: 'PrivateKey' object has no attribute '_sign'`

It looks like for some reason the SignMixin does not get added to the object type on construction and I am not really sure why. 

The incoming pk also has attributes `ObjectClass`, `Value`, `KEY_TYPE` 

I know I should just generate keypairs on the HSM instead, but I am trying to compare HSM signing R/S values to another signing.

Any ideas here?

**Comment by danni** [comment]
Did we ever conclude what was going on here?

**Comment by conscott** [comment]
No exactly, but I found another satisfactory path for what I was trying to test. Thank you for the feedback, I will close the ticket.
