### ISSUE TITLE
missing secp256k1 curve

### ISSUE THREAD

**Issue by nkostoulas** [danni/python-pkcs11#34]
Hello

I'm attempting the following:

```
# Generate an EC keypair in this session from a named curve
    ecparams = session.create_domain_parameters(
        pkcs11.KeyType.EC, {
            pkcs11.Attribute: ec.encode_named_curve_parameters('secp256k1'),
        }, local=True)
    pub, priv = ecparams.generate_keypair()
```

but I get the error:
`ValueError: asn1crypto.keys.NamedCurve._map does not contain an entry for "secp256k1"`

Isn't secp256k1 supported? I saw it was included here https://python-pkcs11.readthedocs.io/en/latest/opensc.html.

**Comment by danni** [comment]
This is missing from `asn1crypto`. You'll need to give the ASN.1 [OID of the curve](https://www.flexiprovider.de/CurveOIDs.html), which is [1.3.132.0.10](http://oid-info.com/get/1.3.132.0.10).

You can file a bug with `asn1crypto` to add the OID to the map.

**Comment by nkostoulas** [comment]
Hey thanks for the reply. I figured it's with asn1crypto but wasn't sure if it's because they don't have it or it's not supported.

Thanks for providing the curve name, I couldn't find it anywhere! Is there a source for getting these?

**Comment by danni** [comment]
The list of curve specs worth mentioning (and the rating of the curves therein) is at https://safecurves.cr.yp.to/ Some curves have multiple names, depending on the spec they're mentioned in, but ideally the curve authors should have used the same OID. You should be able to look up their names in the OID database.

In case it wasn't clear above, you should be able to pass an OID as a string to `encode_named_curve_parameters` (again this is handled by `asn1crypto`), but I notice there's no longer a test for it in the codebase.

**Comment by nkostoulas** [comment]
Yea I tried passing '1.3.132.0.10' to 'encode_named_curve_parameters' and it silently succeeds. Also seems to work fine with my pkcs11 interface so it's all good!

**Comment by nkostoulas** [comment]
Getting it added https://github.com/wbond/asn1crypto/pull/130
