### ISSUE TITLE
Why could PKCS11_TOKEN_PIN equal None?

### ISSUE THREAD

**Issue by keldonin** [danni/python-pkcs11#37]
Hi @danni,

I was wondering which specific use case would require a `None` value for `PKCS11_TOKEN_PIN`? Most tests would fail on a decent PKCS#11 implementation, so is it addressing a specific one?
https://github.com/danni/python-pkcs11/blob/82cf55683bedc7a662de7351d5db9ff07bb6248d/tests/__init__.py#L20

**Comment by danni** [comment]
Passing None means to skip login to the session.

**Comment by keldonin** [comment]
So, when I run tests without defining a user PIN for the token (i.e. `PKCS11_TOKEN_PIN` equals `None`), many (but not all) fail:
```
...
test_encrypt (tests.test_aes.AESTests) ... ERROR
test_encrypt_big_string (tests.test_aes.AESTests) ... ERROR
test_encrypt_stream (tests.test_aes.AESTests) ... ERROR
test_encrypt_whacky_sizes (tests.test_aes.AESTests) ... ERROR
test_sign (tests.test_aes.AESTests) ... ERROR
test_sign_stream (tests.test_aes.AESTests) ... ERROR
test_wrap (tests.test_aes.AESTests) ... ERROR
test_encrypt_oaep (tests.test_rsa.RSATests) ... ERROR
test_encrypt_too_much_data (tests.test_rsa.RSATests) ... ERROR
test_key_wrap (tests.test_rsa.RSATests) ... ERROR
test_sign_default (tests.test_rsa.RSATests) ... ERROR
test_sign_pkcs_v15 (tests.test_rsa.RSATests) ... ERROR
test_sign_pss (tests.test_rsa.RSATests) ... ERROR
test_sign_stream (tests.test_rsa.RSATests) ... ERROR
...
```

Should there be some decorator to skip tests where a PIN is actually needed?

**Comment by danni** [comment]
It really depends on the implementation you're testing against.

**Comment by keldonin** [comment]
..are you suggesting some implementations aren't requiring a C_Login() to interact with the private objects? That would be pretty much non compliant with the specs.

I was only suggesting (and volunteering) to add some decorators around these test cases that require C_Login(). If no password is given, fair enough, these would be skipped.

**Comment by danni** [comment]
Just that there's some `C_Login` implementations we're not handling yet (e.g. Out of Band), so I wouldn't go adding a lot of decorators for it. At the moment not supplying a pin causes it to skip of `C_Login`, and I'm pretty sure I've seen a USB key where everything was a public object.

**Comment by keldonin** [comment]
OK, so let's leave it as it is for now. Thanks for the rationale.
