### ISSUE TITLE
Reading Token information

### ISSUE THREAD

**Issue by Ovomaltine85** [danni/python-pkcs11#4]
Hi!
I want to retrieve information about a certain token like serial number, manufacturer etc.
If I select a token with `get_token(token_label='somelabel')` I only can read token's label with `token.label`, but all other token data like token manufacturer, model or serial number is empty.

Hasn't it just been implemented or do I forget something?

**Comment by danni** [comment]
This has been implemented, but probably you've hit a bug (there's some weird UTF-8 decoding bugs I found with this info on various devices). What HSM are you using?

**Comment by Ovomaltine85** [comment]
I'm using SoftHSM2

**Comment by danni** [comment]
Oh! They're on `token.slot`.

e.g.

```
>>> token.slot.manufacturer_id
'OpenSC Project'
```

**Comment by Ovomaltine85** [comment]
Thank you, that works! But I'm still missing how to get the serial number of the token. Is there also the chance to retrieve this information?

**Comment by danni** [comment]
This is `token.serial`, but it looks like there's a bug.
