### ISSUE TITLE
Signature object type conversion

### ISSUE THREAD

**Issue by ftbarata** [danni/python-pkcs11#40]
Hi @danni  ,

I'm stuck on this thread below and it seems for me that some conversion of the return of the sign() is needed to make everything works.

https://github.com/wbond/asn1crypto/issues/132

Do you mind to take a look at the last post on this thread?

**Comment by wbond** [comment]
I don't believe the issue has anything to do with the data coming out of pkcs11, @ftbarata.

**Comment by ftbarata** [comment]
@wbond  sorry again. I'm so tired trying to make it works. I hate annoying you in this way. I don't know what else to do. I feel that 99% is done and I'm very close to finish it. Could you give me any direction?

**Comment by danni** [comment]
It looks like you solved your issue?

**Comment by ftbarata** [comment]
Yeas @danni ! Thank you so much for helped me before.
