### ISSUE TITLE
Getting NameError: name 'path' is not defined with python-pkcs11 in windows

### ISSUE THREAD

**Issue by kalyank23** [danni/python-pkcs11#41]
I installed latest version of python-pkcs11 in my windows machine. It recently added this feature to install in windows. But I am getting the below error

Traceback (most recent call last):
  ```
File "<stdin>", line 1, in <module>
  File "C:\Users\Downloads\python-pkcs11-master\pkcs11\__init__.py", line 32, in lib
    _lib = _pkcs11.lib(so)
  File "pkcs11\_pkcs11.pyx", line 1235, in pkcs11._pkcs11.lib.__cinit__
    self._load_pkcs11_lib(so)
  File "pkcs11\_pkcs11.pyx", line 1200, in 
    pkcs11._pkcs11.lib._load_pkcs11_lib
  raise RuntimeError("Cannot open library at {}: {}".format(path, self._winerrormsg()))
NameError: name 'path' is not defined
```

And my

`os.environ['PKCS11_MODULE'] = 'C:\\Windows\\System32\\opensc-pkcs11.dll'`

which is correct file path, could you let me know if you can help me with this issue

**Comment by keldonin** [comment]
There is an issue, at this line (when attempting to raise an exception):

https://github.com/danni/python-pkcs11/blob/4e5782c306ca755b61e0c677c77b40c91d8b6ceb/pkcs11/_pkcs11.pyx#L1200

`path` should be replaced by `so`, hence the `NameError` exception triggered while raising a `RuntimeError`. But that doesn't address your fundamental issue.
In waiting for a PR to fix this, can you do the following:
 - edit `_pkcs11.pyx` at line 1200 and replace `path`with `so`
 - rebuild the project
 - execute again and report the exception message you get? The Windows error message might help finding out why it didn't work.

**Comment by keldonin** [comment]
@kalyank23 : it might be that you are trying to load a 32 bits DLL from a 64 bits python. This is impossible. In which case, you either need to load the 64 bits DLL (often suffixed with `-x64` in the name), or use a 32 bits cpython version.

**Comment by kalyank23** [comment]
@keldonin, in the code that I took from gihub, has 'path' instead of 'so', which caused the issue. But it got gixed now after replacing 'path' with 'so'. Thanks for your response.
