### ISSUE TITLE
Convert  pkcs11.types.PrivateKey to PrivateKeyInfo or PrivateKey

### ISSUE THREAD

**Issue by ftbarata** [danni/python-pkcs11#43]
Hi, I'm building a CertificateListBuilder but it requires the pkcs11.types.PrivateKey to  be an instance of asn1crypto.keys.PrivateKeyInfo or oscrypto.asymmetric.PrivateKey.

How to do it? Is it possible?

**Comment by danni** [comment]
I assume you're trying to sign the certificate? **You never want to exfiltrate the private key from your HSM, and often you can't**. You will need to sign the certificate inside the HSM. There's an example of doing this in the tests, you need to dump the `TBSCertificate`, sign that, and then add that signature, along with the `TBSCertificate` into the `Certificate`.

**Comment by ftbarata** [comment]
Hello @danni , thank you again for reply. I know that it's almost impossible to extract the privkey from the pkcs11 device, and I'm worried about this. Take a look at this snippet:

```
builder = CertificateListBuilder(
crl_distribution_point,
asymmetric.load_certificate(mycert_pem.encode()),
int(crl_serial)
)
privkey = encode_rsa_public_key(priv)
certificate_list = builder.build(priv)
```
As you can see, I'm not using the TBSCertificate. The privkey needs to be passed in as an argument.  I have a bad feeling that's impossible to use CertificateListBuilder and python pkcs11 together, right? If so, is there any alternative?

**Comment by danni** [comment]
The certificates are from `oscrypto`, so you can definitely access the underlying X.509 structures. You could start by looking at the implementation of `build()` and see how it accesses the signing code.

Furthermore, your example encodes a private key using the public key data structure. This is not going to work for you.

**Comment by ftbarata** [comment]
@danni , Yeah, the encode_rsa_public_key was a mistake, I'd had to remove before. I was just making some tests. So, thanks again. I'll see what I can do...

**Comment by wbond** [comment]
Just for the record in case someone else is looking at this issue, the canonical issue tracking the ability for the modularcrypto packages to use non-oscrypto signing is https://github.com/wbond/asn1crypto/issues/6.
