### ISSUE TITLE
TokenNotRecognized

### ISSUE THREAD

**Issue by ftbarata** [danni/python-pkcs11#47]
Hi. I known that in requirements that python version must be < 3.6.
However,  thanks to https://github.com/joernheissler/cryptokey, I've changed the CertificateListBuilder.build() to make the signature works with pkcs11 device. In order to do this, I had to use cryptokey and python 3.7.0.
However I have a pkcs11 session working in a Debian Strech 9.8 64 bits and the other token, same model, same python 3.7.0 version, throwing TokenNotRecognized exception in a Ubuntu 16.04 LTS 64 bits.
Here are the requirements installed:
asn1crypto==0.24.0
cached-property==1.5.1
certifi==2018.11.29
cffi==1.12.2
chardet==3.0.4
configobj==5.0.6
cryptography==2.6
idna==2.8
oscrypto==0.19.1
pycparser==2.19
pyOpenSSL==19.0.0
python-dateutil==2.8.0
python-pkcs11==0.5.0
requests==2.21.0
six==1.12.0
Unidecode==1.0.23
urllib3==1.24.1

What could I do to try to make it works in python 3.7.0?

**Comment by ftbarata** [comment]
@danni , I guess the problem is not python version. I've installed the pytho 3.5.4 and I'm getting the same problem TokenNotRecognized exception. It was working before. I tried to run it in a vbox debian stretch , to make this enviroment as identical as possible to the physical host running debian stretch,wich is working.
Any ideas?

**Comment by danni** [comment]
Yep, that seems like an issue in SafeNet. Is the token initialised?

**Comment by ftbarata** [comment]
Hi @danni ,
I did:
pkcs11-tool -l  --module /usr/lib/libaetpkcss.so.3 -T  and before it asks for the pin, I get:
```
Available slots:
Slot 0(0xcd01): AKS ifdh [Main Interface] 00 00
  (token not recognized)
error: PKCS11 function C_OpenSession failed: rv = CKR_SLOT_ID_INVALID(0x3)

Aborting
```

**Comment by danni** [comment]
I don't know, but it's certainly belong the scope of python-pkcs11. You should take the problems up with your PKCS#11 vendor.
