### ISSUE TITLE
AES operations on Nitrokey Pro 2

### ISSUE THREAD

**Issue by batuhanceylan** [danni/python-pkcs11#48]
Is there anyone who tested AES encryption/decryption on Nitrokey Pro 2 using python-pkcs11?

I'm aware it's written N/A on [Python-PKCS#11 compatibility table](https://python-pkcs11.readthedocs.io/en/latest/index.html#tested-compatibility) but [here](https://support.nitrokey.com/t/aes-encryption-and-key-permission-management-support/1677/4) it is written that Nitrokey pro 2 is in fact a OpenPGP Card v3.3 and the [specification](https://gnupg.org/ftp/specs/OpenPGP-smart-card-application-3.3.1.pdf) state AES operations on pages 57-60. I believe it should work. I'm able to do it on softhsm but I would like to know whether it's possible before investing in the product.

**Comment by danni** [comment]
I don't know about the Pro 2, I have a Nitrokey HSM, which *does not* feature symmetric encryption, nor the public side of asymmetric encryption. Meaning that it is only capable of private key operations, and you must do the public key operations yourself.

It's worth noting that the Nitrokey HSM is very slow. You wouldn't want to do a lot of crypto on it. If you were looking to do symmetric crypto you could generate a symmetric session key using diffie-hellman against a private key on the device and then do the AES on the computer. There's an example of this in the tests.

I do use my Nitrokey HSM with PGP, which operates in a way very similar to this.
