### ISSUE TITLE
CKR_ARGUMENTS_BAD after destroying item inside get_objects

### ISSUE THREAD

**Issue by wjmelements** [danni/python-pkcs11#59]
I've noticed a pattern: that if I delete a key inside of a get_objects iteration and I have other keys, it hangs for a long time and then I get CKR_ARGUMENTS_BAD from C_FindObjects. I'm using CloudHSM which doesn't support many pkcs11 features, but I suspect this issue may also happen on other products.

Here is an excerpt from a unit test failure stacktrace:
```
/lib/hsm.py:165: in delete_key
    for public_obj in session.get_objects(PUBLIC_KEY_OBJECTS_FILTER):
pkcs11/_pkcs11.pyx:275: in pkcs11._pkcs11.SearchIter.__next__
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   pkcs11.exceptions.ArgumentsBad

pkcs11/_errors.pyx:88: ArgumentsBad
```

**Comment by wjmelements** [comment]
It has happened when deleting the middle of three.

**Comment by danni** [comment]
Yeah I'm not surprised this fails. You generally can't mix and match PKCS#11 streaming data commands with other commands.

**Comment by danni** [comment]
I should add, there's also an operations lock to prevent multiple coroutines from accessing the session simultaneously. So you've likely got a re-enterancy problem if you're trying to call another routine from inside of the iterator.

**Comment by wjmelements** [comment]
So, I can work around this by deleting the objects after the iteration?

**Comment by danni** [comment]
Yes. Once you’re done with the current operation. You can also iterate a `list()` so that the operations are sequenced.  

I should probably update the docs with this information, and see if there’s a way to detect you’re deadlocking yourself.

**Comment by wjmelements** [comment]
Thanks
