### ISSUE TITLE
ECDSA Example code fails with CKR_TEMPLATE_INCOMPLETE

### ISSUE THREAD

**Issue by Shirikatsu** [danni/python-pkcs11#62]
I've taken a modified version of the example code for ECDSA:

```python
#!/usr/bin/python3
import pkcs11
from pkcs11 import util
from pkcs11.util import ec

lib = pkcs11.lib("/usr/lib/softhsm/libsofthsm2.so")
token = lib.get_token(token_label='test')
data = b'INPUT DATA'

# Open a session on our token
with token.open(user_pin='1234') as session:
    # Generate an EC keypair in this session from a named curve
    ecparams = session.create_domain_parameters(pkcs11.KeyType.EC, {pkcs11.Attribute: pkcs11.util.ec.encode_named_curve_parameters('secp256r1'),}, local=True)
    pub, priv = ecparams.generate_keypair()
    # Sign
    signature = priv.sign(data)
```

And running this fails with:

```
Traceback (most recent call last):
  File "./ecdsa.py", line 14, in <module>
    pub, priv = ecparams.generate_keypair()
  File "pkcs11/_pkcs11.pyx", line 720, in pkcs11._pkcs11.DomainParameters.generate_keypair
  File "pkcs11/_errors.pyx", line 88, in pkcs11._pkcs11.assertRV
pkcs11.exceptions.TemplateIncomplete
```

`Python 3.6.8` using `v0.5` of this library with softhsm `v2.5.0`.

What am I missing?

**Comment by danni** [comment]
I suspect you're missing the mechanism.

See [test_ecc.py:22](https://github.com/danni/python-pkcs11/blob/master/tests/test_ecc.py#L22)

**Comment by Shirikatsu** [comment]
In the test file though, the mechanism is defined after the key generation which is the line that the above code fails on.

It seems to be missing attributes from the template that is being passed in that softhsm may require.

**Comment by danni** [comment]
There's an environment variable to increase the debugging returned by softhsm through stderr. This might help to understand what's lacking.

**Comment by johughes99** [comment]
I also have this problem using the publicised example.  

Being very familiar with the C/C++ pkcs#11 world I thought I would use the pkcs11-spy facility which intercepts the exact pkcs#11  calls (and associated parameters) being passed into the relevant PKCS#11 library.  It seems quite obvious what is happening (or at least so I think)

The pkcs11.pyx module is not properly populating the two templates being provided to the C_GenerateKeyPair call. In particular the CKA_ECDSA_PARAMS and CKA_KEY_TYPE  attributes are missing from the public key template and CKA_KEY_TYPE is missing from the private key template.  To get around this you will have to explicitly include the template in the generate_keypair call.

**Comment by danni** [comment]
Okay there is in fact a typo in this example, it's missing the attribute name.

It should look like this: https://github.com/danni/python-pkcs11/blob/master/tests/test_ecc.py#L24

Pull request to fix the README would be greatly appreciated.

**Comment by Sidxzx** [comment]
Hello,

I have the same error:
```
Traceback (most recent call last):
  File "test1.py", line 29, in <module>
    pub, priv = parameters.generate_keypair()
  File "pkcs11/_pkcs11.pyx", line 741, in pkcs11._pkcs11.DomainParameters.generate_keypair
  File "pkcs11/_errors.pyx", line 88, in pkcs11._pkcs11.assertRV
pkcs11.exceptions.TemplateInconsistent
```
Can someone please provide a complete template ?

**Comment by danni** [comment]
README has been updated to match documentation.
