### ISSUE TITLE
session.get_objects() throws MemoryError

### ISSUE THREAD

**Issue by akirashimosoeda** [danni/python-pkcs11#70]
Somehow, I can't get the objects inside my smart card. I'm currently using a 8gb ram with around 4gb available memory. What am I doing wrong?

I also tried overcommiting the memory by running `echo 1 > /proc/sys/vm/overcommit_memory`, but still throws the same error.

```
Traceback (most recent call last):
  File ".../run.py", line 14, in <module>
    obj = next(session.get_objects({ pkcs11.Attribute.CLASS: pkcs11.ObjectClass.PUBLIC_KEY, pkcs11.Attribute.LABEL: label}))
  File "pkcs11/_pkcs11.pyx", line 271, in pkcs11._pkcs11.SearchIter.__next__
  File "pkcs11/_pkcs11.pyx", line 564, in pkcs11._pkcs11.Object._make
  File "pkcs11/_pkcs11.pyx", line 608, in pkcs11._pkcs11.Object.__getitem__
  File "pkcs11/_utils.pyx", line 11, in pkcs11._pkcs11.CK_BYTE_buffer
  File "stringsource", line 176, in View.MemoryView.array.__cinit__
MemoryError: unable to allocate array data.
```

**Comment by danni** [comment]
There should be no need to overcommit memory, presumably the value for the array size is invalid. You're going to have to debug why. I would start with finding out how much memory we asked for.

My guess is something is PKCS#11 has been compiled with the wrong word length or similar. What HSM are you using?

**Comment by akirashimosoeda** [comment]
I'm using Feitian ePass2003. The manufacturer gave me a module called `libcastle.so.1.0.0`.

**Comment by danni** [comment]
It's compiled for the same word size as you're using here?

**Comment by akirashimosoeda** [comment]
```
$ file /usr/local/lib/libcastle.so.1.0.0
/usr/local/lib/libcastle.so.1.0.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, stripped
```
python-pkcs11 is being installed in the `lib` directory using pip, which I think is only for 32 bit libs.

**Comment by danni** [comment]
The directory name has no actual bearing on the what's in the binary headers.

You might have to add some debugging and find out what's going on. Unfortunately I don't have your HSM so I can't replicate the setup.

**Comment by akirashimosoeda** [comment]
Ok, it seems like I'm receiving a very big number, the value varies around `139882789863428` on `template.ulValueLen`, which is given by C_GetAttributeValue from OpenSC.

**Comment by danni** [comment]
Okay so I think the problem is in the initialisation of the `CK_ATTRIBUTE`. `ulValueLen` contains a bunch of higher bit values. Try adding `template.ulValueLen = <CK_ULONG> 0` after `template.pValue = NULL` (line 609).

**Comment by akirashimosoeda** [comment]
Amazing, it solved the issue.
