### ISSUE TITLE
Can't sign if PIN is required per action

### ISSUE THREAD

**Issue by roboter202** [danni/python-pkcs11#72]
If a PIN is required per action like on the Digital Signature slot on a Yubikey [https://developers.yubico.com/PIV/Introduction/Certificate_slots.html](yubikey PIV slots) 
sign will throw a UserNotLoggedIn exception.

```
with token.open(rw=True,user_pin='<PIN>') as ses:
    private = ses.get_key(label='SIGN key')
    sig = private.sign('<data>') `

```
throws 

```
Traceback (most recent call last):
  File "./script.py", line 21, in <module>
    sig = private.sign('<data>') 
  File "/usr/lib/python3.8/site-packages/pkcs11/types.py", line 936, in sign
    return self._sign(data, **kwargs)
  File "pkcs11/_pkcs11.pyx", line 900, in pkcs11._pkcs11.SignMixin._sign
  File "pkcs11/_pkcs11.pyx", line 910, in pkcs11._pkcs11.SignMixin._sign
  File "pkcs11/_errors.pyx", line 88, in pkcs11._pkcs11.assertRV
pkcs11.exceptions.UserNotLoggedIn
```

signing using this key and mechanism works when using the pkcs11-tool

**Comment by danni** [comment]
Yeah, I'm familiar with this particular spec requirement, although I'm not sure how to handle it in this type of setup. Do we hold the pin in memory? Do we add a new API that users can use to submit a pin when required? I'm happy to accept a pull request to implement something here.

**Comment by roboter202** [comment]
I don't like the idea of holding the PIN in memory. This should be handled in the program using this interface. Either add an optional pin argument to the function (and the others) or a callback that is invoked on pin requirement. The callback makes the fact that a PIN was used for this action more obvious.

**Comment by danni** [comment]
I think a callback API is probably outside the scope of this API, because I'm not sure we can rely on the return code from the PKCS#11 implementor. Also it creates weirdness for different async models. Probably the easiest option is to have a new API that let's you send login detail whenever you desire and to implement the callback/exception handling on the app-side in whatever your async loop is.
