### ISSUE TITLE
No support for Python 3.8 on Windows

### ISSUE THREAD

**Issue by gleonhard** [danni/python-pkcs11#73]
I'm missing support for Python 3.8.
When trying to install using pip on 3.8 I get the following error:
_ERROR: Command errored out with exit status 3221225477: python setup.py egg_info Check the logs for full command output._
When trying to build source I get a segmentation fault.

Is this something that will be supported in the future or is the project dead - no version release since February 2018.
As a side note it would be nice to get the last patch from "master" released.

**Comment by danni** [comment]
The project is a bit haphazardly maintained at the moment. I'll try and get some releases of master out in the near future.

Do you any have more logging with your build error? It might be a matter of upgrading the required Cython version to work with Python 3.8.

**Comment by gleonhard** [comment]
That would be appreciated - at least the latest fix to master, which fixed the issue on windows.
Regarding the build issues I've attached logs for both pip install and python build executions. After analysing the build issue a bit further the module seems to work with Python 3.8.1, even with the segmentation fault error.
[build.log](https://github.com/danni/python-pkcs11/files/4218478/build.log)
[install.log](https://github.com/danni/python-pkcs11/files/4218479/install.log)
[pip_master.log](https://github.com/danni/python-pkcs11/files/4218480/pip_master.log)

**Comment by danni** [comment]
Have you tried upgrading Cython ?

**Comment by danni** [comment]
[v0.6.0](https://github.com/danni/python-pkcs11/releases/tag/v0.6.0) has been released, which upgrades Cython.
