### ISSUE TITLE
tested Equinix SmartKey - works

### ISSUE THREAD

**Issue by tomholub** [danni/python-pkcs11#74]
Thank you for your great work on this library!

Equinix has a 30-day trial at https://eu.smartkey.io/ that includes an pkcs11 interface, which I was able to test against. I downloaded their `./smartkey_pkcs11_3.11.1281.so` from http://support.smartkey.io/smartkey/developers-guide-pkcs11.html and set it up with a certificate based authentication.

```python
import pkcs11.mechanisms

lib = pkcs11.lib("./smartkey_pkcs11_3.11.1281.so")
token = list(lib.get_tokens())[0]

with token.open(user_pin='file://smartkey-pkcs11.cfg') as session:
	plaintext = b"input data"
	stored_key = session.generate_key(pkcs11.KeyType.AES, 256) # Generate an AES key in this session
	iv = session.generate_random(128)  # AES blocks are fixed at 128 bits
	crypttext = stored_key.encrypt(plaintext, mechanism_param=iv)
	decrypted = stored_key.decrypt(crypttext, mechanism_param=iv)
	if decrypted != plaintext:
		raise Exception('decrypted data unexpectedly different')
	print("pkcs11 encrypt/decrypt pass")
```

Where `smartkey-pkcs11.cfg` is:
```conf
api_endpoint = "https://api.eu.smartkey.io"
cert_file = "./pkcs11-test-app.cer"
key_file = "./pkcs11-test-app.pem"
app_id = "279a75ab-0886-4aac-a198-c087e921c21e"

[log]
file = "./pkcs11-lib.log"
```
You may want to try running your tests against it.

**Comment by danni** [comment]
Thanks for this info. You can run the test suite against it yourself, have a look at how we set up the testsuite in [`test.sh`](https://github.com/danni/python-pkcs11/blob/master/tools/nfast/test.sh) for inspiration.
