### ISSUE TITLE
Fail to load .so in both in MAC & Ubuntu

### ISSUE THREAD

**Issue by applezhp** [danni/python-pkcs11#76]
The info from Mac:

MAC catalina 10.15.2, Python 3.7.4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkcs11/__init__.py", line 32, in lib
    _lib = _pkcs11.lib(so)
  File "pkcs11/_pkcs11.pyx", line 1243, in pkcs11._pkcs11.lib.__cinit__
  File "pkcs11/_pkcs11.pyx", line 1221, in pkcs11._pkcs11.lib._load_pkcs11_lib
RuntimeError: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyKCS11/_LowLevel.cpython-37m-darwin.so is not a PKCS#11 library: b'dlsym(0x7fa09ed3a740, C_GetFunctionList): symbol not found'

Similar under Ubuntu 16.04 with python3.5

**Comment by figbux** [comment]
Hello @applezhp 
By looking the error code, it seems like your pkcs11-library doesn't have `C_GetFunctionList`. From this, I'd say the problem is in the pkcs11 library. Have you tried running it against softhsmv2?
Besides that, it would be nice to get some info about:
- your code
- your library

**Comment by applezhp** [comment]
Yeah, I have tried both python-pkcs11 & PyKCS11 and got the similiar error. I realize that I need to install opensc to work with smart card and doing the related jobs now.

**Comment by applezhp** [comment]
Finally I got the .so package from the supplier, it works! My U-token is epass2000Auto by Feitian. If somebody else need the .so file for linux, I can share it!

**Comment by 773517913** [comment]
Hello @applezhp 
Thanks a lot, I'd become appreciated if you can send me the working .so file. Can you please share it via here, or see my email in my profile.
