### ISSUE TITLE
crash after loading pkcs11 library in cygwin

### ISSUE THREAD

**Issue by ablam** [danni/python-pkcs11#80]
In Cygwin environment python crashes during loading any pkcs11 library - tested on current Cygwin release, 64-bit, windows 10 pro 64-bit.
It is caused by #pragma pack in cryptoki.h - after commenting it out, everything works as it used to.

**Comment by danni** [comment]
That sounds like bad setup of the `#define`s. `cryptoki.h` is an extern file. Have a look at what `#define`s are required and see if you can make `setup.py` set them?

**Comment by ablam** [comment]
What is the source of cryptoki.h - in header there is a guy Eric Devolder, but his github repo is just fork of other commonly known projects (including yours)?
This file is probably based on file from pkcs11-tools from mastercard, but it's meant for windows only: https://github.com/Mastercard/pkcs11-tools/blob/master/include/cryptoki/cryptoki.h 
Anyway my guess is that cygwin no longer uses same defs as windows (I had similar problem with lib11, where cygwin was also treated as windows, which is wrong) and additional #define is wrong.

my change:
```
#if defined(_MSC_VER) && defined(_WIN32) /* we are compiling using Visual C */
#pragma pack(push, cryptoki, 1)
//#elif defined(__CYGWIN__)
//#pragma pack(push, 1)
#endif

#include "pkcs11.h"

#if defined(_MSC_VER) && defined(_WIN32) /* we are compiling using Visual C */
#pragma pack(pop, cryptoki)
//#elif defined(__CYGWIN__)
//#pragma pack(pop)
#endif
```

Is there a way to override it from setup.py? 
Since it's gcc/cython code it might be hard, there is switch:
-undef - Do not predefine any system-specific or GCC-specific macros. The standard predefined macros remain defined. 
But it will throw away usefull stuff as well

**Comment by danni** [comment]
The source is the cryptoki spec. If something has changed in cygwin there could be an updated version. However I would assume the problem is more in the compiler arguments we’re passing in setup.py before I’d patch the spec headers. This could require a bit of trial and error.

**Comment by danni** [comment]
Try updating the headers and see what it does?

**Comment by keldonin** [comment]
@ablam Compiling python-pkcs11 under Cygwin has limited value. This is because the PKCS#11 specification is aliasing most of its types from `CK_ULONG`, defined as `unsigned long int`,  and on x86_64 platforms, GCC/Clang (the compiler under Cygwin) and MSVC have different sizes for it. Consequently, you will never be able to use a PKCS#11 library from Cygwin unless it has been compiled under Cygwin. Most PKCS#11 libraries are compiled under MSVC on the Windows platform. 

This may explain your library crash after loading.
