### ISSUE TITLE
C_FindObjects not implemented?

### ISSUE THREAD

**Issue by maestrx** [danni/python-pkcs11#9]
Hello,

am I blind  or this library doesnt not support finding objects already existing using C_FindObjects pkcs11 native method? :)

It looks like it does not when I checked the code ... Is this an oversight? Could this be changed?

Can I help ?

Thank you

**Comment by danni** [comment]
Hi, it's called `session.get_objects()`.

http://python-pkcs11.readthedocs.io/en/latest/api.html#pkcs11.Session.get_objects

It's here in the code: https://github.com/danni/python-pkcs11/blob/master/pkcs11/_pkcs11.pyx#L253
