### ISSUE TITLE
Any way to restrict the range of private key when generating key pair?

### ISSUE THREAD

**Issue by kigawas** [danni/python-pkcs11#96]
Generally a private key of secp256k1 should be `0 < secret < group order` and the group order is `int('fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141', 16)`.

Does there exist a method to make sure the key is generated within this range?

**Comment by danni** [comment]
We leave enforcing rules up to the HSM / PKCS#11 library.
